//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaje
    {
        public int MesajID { get; set; }
        public Nullable<int> ProgramareID { get; set; }
        public Nullable<int> ExpeditorID { get; set; }
        public string Continut { get; set; }
        public Nullable<System.DateTime> DataOra { get; set; }
        public Nullable<bool> IsCitit { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        public virtual Programari Programari { get; set; }
    }
}
