//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programari()
        {
            this.FiseMedicales = new HashSet<FiseMedicale>();
            this.Serviciis = new HashSet<Servicii>();
            this.Mesajes = new HashSet<Mesaje>();
        }
    
        public int ProgramareID { get; set; }
        public Nullable<int> ClinicaID { get; set; }
        public Nullable<int> MedicID { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public System.DateTime DataOra { get; set; }
        public string Motiv { get; set; }
        public string Status { get; set; }
    
        public virtual Animale Animale { get; set; }
        public virtual Clinici Clinici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiseMedicale> FiseMedicales { get; set; }
        public virtual Medici Medici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicii> Serviciis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesaje> Mesajes { get; set; }
    }
}
