//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remindere
    {
        public int ReminderID { get; set; }
        public int AnimalID { get; set; }
        public int MedicID { get; set; }
        public string Mesaj { get; set; }
        public System.DateTime DataLimita { get; set; }
        public Nullable<bool> IsCitit { get; set; }
        public Nullable<System.DateTime> DataCreare { get; set; }
    
        public virtual Animale Animale { get; set; }
        public virtual Medici Medici { get; set; }
    }
}
