//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicii()
        {
            this.DetaliiFisa_Servicii = new HashSet<DetaliiFisa_Servicii>();
            this.Programaris = new HashSet<Programari>();
        }
    
        public int ServiciuID { get; set; }
        public Nullable<int> ClinicaID { get; set; }
        public string Denumire { get; set; }
        public decimal PretStandard { get; set; }
        public Nullable<int> DurataEstimataMinute { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiFisa_Servicii> DetaliiFisa_Servicii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari> Programaris { get; set; }
    }
}
