//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocuri()
        {
            this.DetaliiFisa_Materiale = new HashSet<DetaliiFisa_Materiale>();
        }
    
        public int StocID { get; set; }
        public Nullable<int> ClinicaID { get; set; }
        public string DenumireProdus { get; set; }
        public string UnitateMasura { get; set; }
        public Nullable<decimal> CantitateDisponibila { get; set; }
        public Nullable<decimal> PretUnitar { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiFisa_Materiale> DetaliiFisa_Materiale { get; set; }
    }
}
