//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animale()
        {
            this.Programaris = new HashSet<Programari>();
            this.Reminderes = new HashSet<Remindere>();
        }
    
        public int AnimalID { get; set; }
        public Nullable<int> ProprietarID { get; set; }
        public Nullable<int> SpecieID { get; set; }
        public string Nume { get; set; }
        public Nullable<System.DateTime> DataNasterii { get; set; }
        public string Microcip { get; set; }
    
        public virtual Proprietari Proprietari { get; set; }
        public virtual Specii Specii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari> Programaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remindere> Reminderes { get; set; }
    }
}
