//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CereriMedici
    {
        public int CerereID { get; set; }
        public int MedicID { get; set; }
        public int ClinicaID { get; set; }
        public string Status { get; set; }
        public System.DateTime DataCerere { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        public virtual Medici Medici { get; set; }
    }
}
