//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medici()
        {
            this.OrarMedicis = new HashSet<OrarMedici>();
            this.Programaris = new HashSet<Programari>();
            this.Speciis = new HashSet<Specii>();
            this.Clinicis = new HashSet<Clinici>();
            this.Reminderes = new HashSet<Remindere>();
            this.CereriMedicis = new HashSet<CereriMedici>();
        }
    
        public int MedicID { get; set; }
        public Nullable<int> UtilizatorID { get; set; }
        public Nullable<int> ClinicaID { get; set; }
        public string NrParafa { get; set; }
        public string Bio { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrarMedici> OrarMedicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari> Programaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specii> Speciis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinici> Clinicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remindere> Reminderes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CereriMedici> CereriMedicis { get; set; }
    }
}
