//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrarMedici
    {
        public int OrarID { get; set; }
        public Nullable<int> MedicID { get; set; }
        public Nullable<int> ZiSaptamana { get; set; }
        public System.TimeSpan OraInceput { get; set; }
        public System.TimeSpan OraSfarsit { get; set; }
        public Nullable<int> ClinicaID { get; set; }
    
        public virtual Medici Medici { get; set; }
        public virtual Clinici Clinici { get; set; }
    }
}
