//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administratori
    {
        public int AdminID { get; set; }
        public Nullable<int> UtilizatorID { get; set; }
        public Nullable<int> ClinicaID { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
