//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiFisa_Materiale
    {
        public int DetaliuID { get; set; }
        public Nullable<int> FisaID { get; set; }
        public Nullable<int> StocID { get; set; }
        public decimal CantitateConsumata { get; set; }
    
        public virtual FiseMedicale FiseMedicale { get; set; }
        public virtual Stocuri Stocuri { get; set; }
    }
}
