//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiseMedicale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FiseMedicale()
        {
            this.DetaliiFisa_Materiale = new HashSet<DetaliiFisa_Materiale>();
            this.DetaliiFisa_Servicii = new HashSet<DetaliiFisa_Servicii>();
        }
    
        public int FisaID { get; set; }
        public Nullable<int> ProgramareID { get; set; }
        public string Diagnostic { get; set; }
        public string Tratament { get; set; }
        public Nullable<System.DateTime> DataCrearii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiFisa_Materiale> DetaliiFisa_Materiale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiFisa_Servicii> DetaliiFisa_Servicii { get; set; }
        public virtual Programari Programari { get; set; }
    }
}
