//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetCareEntities : DbContext
    {
        public PetCareEntities()
            : base("name=PetCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administratori> Administratoris { get; set; }
        public virtual DbSet<Animale> Animales { get; set; }
        public virtual DbSet<Clinici> Clinicis { get; set; }
        public virtual DbSet<DetaliiFisa_Materiale> DetaliiFisa_Materiale { get; set; }
        public virtual DbSet<DetaliiFisa_Servicii> DetaliiFisa_Servicii { get; set; }
        public virtual DbSet<FiseMedicale> FiseMedicales { get; set; }
        public virtual DbSet<Medici> Medicis { get; set; }
        public virtual DbSet<OrarMedici> OrarMedicis { get; set; }
        public virtual DbSet<Programari> Programaris { get; set; }
        public virtual DbSet<Proprietari> Proprietaris { get; set; }
        public virtual DbSet<Servicii> Serviciis { get; set; }
        public virtual DbSet<Specii> Speciis { get; set; }
        public virtual DbSet<Stocuri> Stocuris { get; set; }
        public virtual DbSet<Utilizatori> Utilizatoris { get; set; }
    }
}
